version: "3"
services:
  zhulong:
    hostname: zhulong
    image: harbor.dazhi100.com/dzyx/zhulong:latest
    container_name: zhulong
    restart: always
    ports:
      - "18010:18010"
      - "20881:20881"
    networks:
      - dzyx-server-network

networks:
  dzyx-server-network:
    external: false
